# kitty.conf

# Font
font_family JetBrains Mono
font_size 12

# Theme
include dracula.conf

# Window
window_padding_width 5
hide_window_decorations yes

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Scrollback
scrollback_lines 10000
